"""
High-level molecular similarity search engine.

This module performs similarity searches over a StructureDatabase
using molecular fingerprints generated by the chemistry pipeline.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Any, Dict, List, Optional

from chemistry.fingerprints import (
    FingerprintGenerator,
    FingerprintResult,
)

from chemistry.similarity import (
    SimilarityCalculator,
    SimilarityResult,
)

from chemistry.structure_database import (
    StructureDatabase,
    StructureRecord,
)

from chemistry.canonicalizer import Canonicalizer

import time

# ------------------------------------------------------------------
# Similarity Search Result
# ------------------------------------------------------------------

@dataclass(frozen=True)
class SimilaritySearchResult:
    """
    Represents the outcome of a similarity search.

    One query fingerprint may produce zero, one, or many
    matching molecular structures.
    """

    # ------------------------------------------------------------
    # Query
    # ------------------------------------------------------------

    query: FingerprintResult

    # ------------------------------------------------------------
    # Search Results
    # ------------------------------------------------------------

    matches: List[SimilarityResult] = field(default_factory=list)

    # ------------------------------------------------------------
    # Search Configuration
    # ------------------------------------------------------------

    metric: str = "Tanimoto"

    threshold: float = 0.70

    top_k: Optional[int] = None

    # ------------------------------------------------------------
    # Runtime
    # ------------------------------------------------------------

    elapsed_time: float = 0.0

    # ------------------------------------------------------------
    # Status
    # ------------------------------------------------------------

    success: bool = True

    error: Optional[str] = None

    # ------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------

    metadata: Dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------
    # Validation Properties
    # ------------------------------------------------------------

    @property
    def has_matches(self) -> bool:
        """
        True if at least one similar structure was found.
        """
        return len(self.matches) > 0


    @property
    def num_matches(self) -> int:
        """
        Number of retrieved matches.
        """
        return len(self.matches)


    @property
    def best_match(self) -> Optional[SimilarityResult]:
        """
        Return the highest-ranked similarity result.
        """

        if not self.matches:
            return None

        return self.matches[0]


    @property
    def best_score(self) -> float:
        """
        Similarity score of the best match.
        """

        if self.best_match is None:
            return 0.0

        return self.best_match.similarity_score


    @property
    def has_error(self) -> bool:
        """
        True if an error occurred.
        """
        return self.error is not None


    @property
    def search_successful(self) -> bool:
        """
        True if the search completed successfully.
        """

        return (
            self.success
            and not self.has_error
        )

    # ------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------

    def summary(self) -> Dict[str, Any]:
        """
        Return a lightweight summary of the search.
        """

        return {
            "success": self.success,
            "metric": self.metric,
            "threshold": self.threshold,
            "top_k": self.top_k,
            "matches_found": self.num_matches,
            "best_score": round(self.best_score, 4),
            "elapsed_time": round(self.elapsed_time, 4),
            "error": self.error,
        }

    def __str__(self) -> str:
        return (
            "SimilaritySearchResult("
            f"matches={self.num_matches}, "
            f"best_score={self.best_score:.4f}, "
            f"metric='{self.metric}', "
            f"success={self.success})"
        )


    def __repr__(self) -> str:
        return self.__str__()

    # ------------------------------------------------------------
    # Copy Helpers
    # ------------------------------------------------------------

    def with_metadata(
        self,
        **metadata: Any,
    ) -> "SimilaritySearchResult":
        """
        Return a new result with additional metadata.
        """

        merged = {
            **self.metadata,
            **metadata,
        }

        return replace(
            self,
            metadata=merged,
        )


    def with_error(
        self,
        message: str,
    ) -> "SimilaritySearchResult":
        """
        Return a failed search result.
        """

        return replace(
            self,
            success=False,
            error=message,
        )



# ------------------------------------------------------------------
# Similarity Searcher
# ------------------------------------------------------------------

class SimilaritySearcher:
    """
    High-level molecular similarity search engine.

    This class searches a StructureDatabase using molecular
    fingerprints and returns ranked SimilaritySearchResult objects.
    """

    DEFAULT_METRIC = "Tanimoto"

    DEFAULT_THRESHOLD = 0.70

    DEFAULT_TOP_K = 10


    def __init__(
        self,
        database: StructureDatabase,
    ) -> None:
        """
        Parameters
        ----------
        database:
            Structure database to search.
        """

        self.database = database

    # ------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------

    @property
    def size(self) -> int:
        """
        Number of structures currently indexed.
        """

        return len(self.database)


    @property
    def searchable_structures(self) -> int:
        """
        Number of searchable structures.
        """

        return len(
            self.database.searchable()
        )


    @property
    def is_empty(self) -> bool:
        """
        True if the database contains no structures.
        """

        return self.size == 0

    # ------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------

    def can_search(self) -> bool:
        """
        Whether the database is ready for searching.
        """

        return (
            not self.is_empty
            and self.searchable_structures > 0
        )

    # ------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------

    def summary(self) -> Dict[str, Any]:
        """
        Return search engine statistics.
        """

        return {
            "database_size": self.size,
            "searchable_structures": self.searchable_structures,
            "ready": self.can_search(),
        }


    def __str__(self) -> str:
        return (
            "SimilaritySearcher("
            f"structures={self.size}, "
            f"searchable={self.searchable_structures})"
        )


    def __repr__(self) -> str:
        return self.__str__()

    # ------------------------------------------------------------
    # Core Search
    # ------------------------------------------------------------

    def search_fingerprint(
        self,
        query: FingerprintResult,
        metric: str = DEFAULT_METRIC,
        threshold: float = DEFAULT_THRESHOLD,
        top_k: Optional[int] = DEFAULT_TOP_K,
    ) -> SimilaritySearchResult:
        """
        Search the database using a query fingerprint.
        """

        start_time = time.perf_counter()

        # --------------------------------------------------------
        # Validate database
        # --------------------------------------------------------

        if not self.can_search():

            return SimilaritySearchResult(
                query=query,
                success=False,
                error="Database contains no searchable structures.",
                elapsed_time=0.0,
            )

        # --------------------------------------------------------
        # Validate query fingerprint
        # --------------------------------------------------------

        if not query.searchable:

            return SimilaritySearchResult(
                query=query,
                success=False,
                error="Query fingerprint is invalid.",
                elapsed_time=0.0,
            )

        matches: List[SimilarityResult] = []

        # --------------------------------------------------------
        # Compare against every searchable structure
        # --------------------------------------------------------

        for record in self.database.searchable():

            if record.fingerprint is None:
                continue

            result = SimilarityCalculator.compare(
                query=query,
                candidate=record,
                metric=metric,
                threshold=threshold,
            )

            if result.is_match:
                matches.append(result)

        # --------------------------------------------------------
        # Rank by similarity
        # --------------------------------------------------------

        matches.sort(
            key=lambda result: result.similarity_score,
            reverse=True,
        )

        # --------------------------------------------------------
        # Apply Top-K
        # --------------------------------------------------------

        if top_k is not None:
            matches = matches[:top_k]

        elapsed = time.perf_counter() - start_time

        return SimilaritySearchResult(
            query=query,
            matches=matches,
            metric=metric,
            threshold=threshold,
            top_k=top_k,
            elapsed_time=elapsed,
            success=True,
        )

    # ------------------------------------------------------------
    # Search Helpers
    # ------------------------------------------------------------

    def search_smiles(
        self,
        smiles: str,
        metric: str = DEFAULT_METRIC,
        threshold: float = DEFAULT_THRESHOLD,
        top_k: Optional[int] = DEFAULT_TOP_K,
    ) -> SimilaritySearchResult:
        """
        Canonicalize a SMILES string, generate its fingerprint,
        and search the database.
        """

        canonical = Canonicalizer.canonicalize(smiles)

        if not canonical.searchable:

            return SimilaritySearchResult(
                query=FingerprintGenerator.failed(
                    "Invalid query SMILES."
                ),
                success=False,
                error="Failed to canonicalize query SMILES.",
            )

        fingerprint = FingerprintGenerator.from_rdkit(
            molecule=canonical.rdkit_molecule,
            canonical_smiles=canonical.canonical_smiles,
        )

        return self.search_fingerprint(
            query=fingerprint,
            metric=metric,
            threshold=threshold,
            top_k=top_k,
        )
    
    def search_record(
        self,
        record: StructureRecord,
        metric: str = DEFAULT_METRIC,
        threshold: float = DEFAULT_THRESHOLD,
        top_k: Optional[int] = DEFAULT_TOP_K,
    ) -> SimilaritySearchResult:
        """
        Search using an existing StructureRecord.
        """

        if record.fingerprint is None:

            return SimilaritySearchResult(
                query=FingerprintGenerator.failed(
                    "Structure has no fingerprint."
                ),
                success=False,
                error="StructureRecord does not contain a fingerprint.",
            )

        return self.search_fingerprint(
            query=record.fingerprint,
            metric=metric,
            threshold=threshold,
            top_k=top_k,
        )
    
    def top_k(
        self,
        query: FingerprintResult,
        k: int = DEFAULT_TOP_K,
        metric: str = DEFAULT_METRIC,
    ) -> SimilaritySearchResult:
        """
        Return the K most similar structures.
        """

        return self.search_fingerprint(
            query=query,
            metric=metric,
            threshold=0.0,
            top_k=k,
        )
    
    def search_database(
        self,
        query: FingerprintResult,
        metric: str = DEFAULT_METRIC,
    ) -> List[SimilarityResult]:
        """
        Search the entire database without filtering by threshold.
        Useful for benchmarking and analysis.
        """

        result = self.search_fingerprint(
            query=query,
            metric=metric,
            threshold=0.0,
            top_k=None,
        )

        return result.matches
    
    # ------------------------------------------------------------
    # Ranking Utilities
    # ------------------------------------------------------------

    @staticmethod
    def rank(
        matches: List[SimilarityResult],
        descending: bool = True,
    ) -> List[SimilarityResult]:
        """
        Return similarity results sorted by similarity score.
        """

        return sorted(
            matches,
            key=lambda result: result.similarity_score,
            reverse=descending,
        )


    @staticmethod
    def filter(
        matches: List[SimilarityResult],
        threshold: float,
    ) -> List[SimilarityResult]:
        """
        Filter similarity results using a minimum similarity score.
        """

        return [
            result
            for result in matches
            if result.similarity_score >= threshold
        ]
    
    # ------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------

    def statistics(self) -> Dict[str, Any]:
        """
        Return statistics describing the current search engine.
        """

        database_stats = self.database.statistics()

        return {
            "database_size": database_stats["total_structures"],
            "searchable_structures": database_stats["searchable_structures"],
            "unique_patents": database_stats["unique_patents"],
            "ready": self.can_search(),
            "default_metric": self.DEFAULT_METRIC,
            "default_threshold": self.DEFAULT_THRESHOLD,
        }
    
    # ------------------------------------------------------------
    # Representation
    # ------------------------------------------------------------

    def __str__(self) -> str:
        stats = self.statistics()

        return (
            "SimilaritySearcher("
            f"structures={stats['database_size']}, "
            f"searchable={stats['searchable_structures']}, "
            f"metric='{stats['default_metric']}'"
            ")"
        )


    def __repr__(self) -> str:
        return self.__str__()